---
# install Docker Compose

- name: download compose binary
  get_url: url="https://github.com/docker/compose/releases/download/1.4.0/docker-compose-Linux-x86_64" dest=/usr/local/bin/docker-compose

- name: chmod compose
  file: path=/usr/local/bin/docker-compose state=file mode=0755
