---
# install docker on AmazonLinux

- name: install docker
  yum: name=docker state=latest

- name: check /etc/sysconfig/docker (tcp)
  command: grep tcp://0.0.0.0:2375 /etc/sysconfig/docker
  register: result
  failed_when: result.rc not in [0, 1]
  always_run: yes
  changed_when: result.rc != 0

- name: edit /etc/sysconfig/docker (tcp)
  replace: >
    dest=/etc/sysconfig/docker
    regexp='^(OPTIONS=".*)"$'
    replace='\1 -H tcp://0.0.0.0:2375"'
  when: result.rc != 0
  notify: restart docker

- name: check /etc/sysconfig/docker (unix domain socket)
  command: grep unix:// /etc/sysconfig/docker
  register: result
  failed_when: result.rc not in [0, 1]
  always_run: yes
  changed_when: result.rc != 0

- name: edit /etc/sysconfig/docker (unix domain socket)
  replace: >
    dest=/etc/sysconfig/docker
    regexp='^(OPTIONS=".*)"$'
    replace='\1 -H unix://"'
  when: result.rc != 0
  notify: restart docker

- name: modify user group
  user: name={{ ansible_env.SUDO_USER }} groups=docker

- name: service start
  service: name=docker state=started
