---

- name: Install docker-engine
  include: docker-engine.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version|int >= 7

- name: Install docker-io
  include: docker-io.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: Install docker
  include: docker.yml
  when:
    - ansible_distribution == "Amazon"
